# Generated by Django 5.2.17 on 2026-08-28 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nome")),
                ("code", models.SlugField(unique=True, verbose_name="código")),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Alteração"),
                            ("REOPEN", "Reabertura"),
                        ],
                        max_length=10,
                        verbose_name="ação",
                    ),
                ),
                ("model_name", models.CharField(max_length=80, verbose_name="modelo")),
                ("object_id", models.CharField(max_length=80, verbose_name="registro")),
                ("reason", models.TextField(blank=True, verbose_name="motivo")),
                (
                    "before_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="valor anterior"
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="novo valor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fleet_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="fleet.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "auditoria",
                "verbose_name_plural": "auditorias",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_name",
                    models.CharField(max_length=160, verbose_name="nome do cliente"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, verbose_name="código do contrato"),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "contracted_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="valor contratado",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="data inicial")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="data final"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("CLOSED", "Encerrado"),
                            ("DRAFT", "Rascunho"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "production_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Valor manual"),
                            ("PER_KM", "Valor por quilômetro"),
                            ("PER_TRIP", "Valor por viagem"),
                            ("MONTHLY", "Valor fixo mensal"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="tipo de produção",
                    ),
                ),
                (
                    "value_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="valor por km",
                    ),
                ),
                (
                    "value_per_trip",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor por viagem",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato",
                "verbose_name_plural": "contratos",
                "ordering": ["-start_date", "client_name"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, verbose_name="nome")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="telefone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("INACTIVE", "Inativo")],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de admissão"
                    ),
                ),
                (
                    "monthly_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor fixo mensal",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "motorista",
                "verbose_name_plural": "motoristas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Remuneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("competence", models.DateField(verbose_name="competência")),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor fixo",
                    ),
                ),
                (
                    "commission_base_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="base da comissão",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="percentual utilizado",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="comissão",
                    ),
                ),
                (
                    "km_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="bônus por quilometragem",
                    ),
                ),
                (
                    "trips_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="bônus por viagens",
                    ),
                ),
                (
                    "other_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="outros bônus",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="total estimado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CALCULATING", "Em cálculo"),
                            ("REVIEW", "Em conferência"),
                            ("APPROVED", "Aprovada"),
                            ("PAID", "Paga"),
                        ],
                        default="CALCULATING",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "calculation_notes",
                    models.TextField(blank=True, verbose_name="memória de cálculo"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remunerations",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "remuneração",
                "verbose_name_plural": "remunerações",
                "ordering": ["-competence", "driver"],
            },
        ),
        migrations.CreateModel(
            name="RemunerationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(verbose_name="vigência inicial")),
                (
                    "effective_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência final"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="prioridade"),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="percentual de comissão",
                    ),
                ),
                (
                    "commission_base",
                    models.CharField(
                        choices=[
                            ("REALIZED", "Valor realizado"),
                            ("DISTANCE", "Quilometragem"),
                            ("TRIPS", "Quantidade de viagens"),
                        ],
                        default="REALIZED",
                        max_length=10,
                        verbose_name="base da comissão",
                    ),
                ),
                (
                    "fixed_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor fixo mensal",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sem bônus"),
                            ("KM", "Por quilometragem"),
                            ("TRIPS", "Por viagens"),
                            ("FIXED", "Bônus fixo"),
                            ("PERCENT", "Bônus percentual"),
                        ],
                        default="NONE",
                        max_length=8,
                        verbose_name="tipo de bônus",
                    ),
                ),
                (
                    "bonus_km_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="limite de quilômetros",
                    ),
                ),
                (
                    "bonus_trip_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="limite de viagens"
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="valor do bônus",
                    ),
                ),
                (
                    "bonus_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="percentual do bônus",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remuneration_rules",
                        to="fleet.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remuneration_rules",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "regra de remuneração",
                "verbose_name_plural": "regras de remuneração",
                "ordering": ["-priority", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin", models.CharField(max_length=120, verbose_name="origem")),
                (
                    "destination",
                    models.CharField(max_length=120, verbose_name="destino"),
                ),
                (
                    "start_odometer",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=12,
                        verbose_name="quilometragem inicial",
                    ),
                ),
                (
                    "end_odometer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="quilometragem final",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="início"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        verbose_name="quilômetros rodados",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="duração"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planejado"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("FINISHED", "Finalizado"),
                            ("CANCELLED", "Cancelado"),
                            ("REOPENED", "Reaberto para correção"),
                        ],
                        default="PLANNED",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="fleet.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "trecho",
                "verbose_name_plural": "trechos",
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=160, verbose_name="local")),
                ("started_at", models.DateTimeField(verbose_name="início")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                ("reason", models.CharField(max_length=160, verbose_name="motivo")),
                (
                    "odometer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="quilometragem",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="fleet.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "parada",
                "verbose_name_plural": "paradas",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identification",
                    models.CharField(max_length=40, verbose_name="identificação"),
                ),
                (
                    "simulated_plate",
                    models.CharField(max_length=20, verbose_name="placa simulada"),
                ),
                ("model", models.CharField(max_length=80, verbose_name="modelo")),
                ("brand", models.CharField(max_length=80, verbose_name="marca")),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ano"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("GASOLINE", "Gasolina"),
                            ("ETHANOL", "Etanol"),
                            ("GNV", "GNV"),
                        ],
                        default="DIESEL",
                        max_length=12,
                        verbose_name="combustível",
                    ),
                ),
                (
                    "tank_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="capacidade do tanque (L)",
                    ),
                ),
                (
                    "current_odometer",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        verbose_name="quilometragem atual",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATING", "Em operação"),
                            ("MAINTENANCE", "Em manutenção"),
                            ("INACTIVE", "Inativo"),
                        ],
                        default="OPERATING",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "financial_status",
                    models.CharField(
                        choices=[("FINANCED", "Financiado"), ("PAID", "Quitado")],
                        default="PAID",
                        max_length=10,
                        verbose_name="situação financeira",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "caminhão",
                "verbose_name_plural": "caminhões",
                "ordering": ["identification"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="fleet.truck",
            ),
        ),
        migrations.CreateModel(
            name="TireExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="data")),
                ("quantity", models.PositiveIntegerField(verbose_name="quantidade")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor"
                    ),
                ),
                (
                    "odometer",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        verbose_name="quilometragem",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="fornecedor"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observação")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tire_expenses",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "despesa com pneu",
                "verbose_name_plural": "despesas com pneus",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("competence", models.DateField(verbose_name="data/competência")),
                (
                    "realized_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor realizado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Em aberto"),
                            ("CONFERRED", "Conferida"),
                            ("APPROVED", "Aprovada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observação")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productions",
                        to="fleet.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productions",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productions",
                        to="fleet.trip",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productions",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "produção financeira",
                "verbose_name_plural": "produções financeiras",
                "ordering": ["-competence"],
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="data e hora"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Aberta"), ("RESOLVED", "Resolvida")],
                        default="OPEN",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrences",
                        to="fleet.trip",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "ocorrência",
                "verbose_name_plural": "ocorrências",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventiva"),
                            ("CORRECTIVE", "Corretiva"),
                            ("TIRES", "Pneus"),
                            ("OIL", "Óleo"),
                            ("BRAKES", "Freios"),
                            ("ENGINE", "Motor"),
                            ("ELECTRIC", "Elétrica"),
                            ("OTHER", "Outros"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("date", models.DateField(verbose_name="data")),
                (
                    "odometer",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        verbose_name="quilometragem",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=240, verbose_name="descrição"),
                ),
                (
                    "workshop",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="oficina"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="valor"
                    ),
                ),
                (
                    "downtime_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tempo parado (dias)"
                    ),
                ),
                (
                    "next_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="próxima data"
                    ),
                ),
                (
                    "next_odometer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="próxima quilometragem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Em aberto"),
                            ("DONE", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DONE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observação")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "manutenção",
                "verbose_name_plural": "manutenções",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Fueling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fueled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="data e hora"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="cidade")),
                ("state", models.CharField(max_length=2, verbose_name="estado")),
                ("station", models.CharField(max_length=160, verbose_name="posto")),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("GASOLINE", "Gasolina"),
                            ("ETHANOL", "Etanol"),
                            ("GNV", "GNV"),
                        ],
                        max_length=12,
                        verbose_name="combustível",
                    ),
                ),
                (
                    "odometer",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=12,
                        verbose_name="quilometragem atual",
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="litros"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor total"
                    ),
                ),
                (
                    "tank_full",
                    models.BooleanField(
                        default=False, verbose_name="tanque completado"
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="preço por litro",
                    ),
                ),
                (
                    "km_per_liter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="km por litro",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="fuelings/%Y/%m/",
                        verbose_name="comprovante",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuelings",
                        to="fleet.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuelings",
                        to="fleet.trip",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuelings",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "abastecimento",
                "verbose_name_plural": "abastecimentos",
                "ordering": ["-fueled_at"],
            },
        ),
        migrations.CreateModel(
            name="FixedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INSURANCE", "Seguro"),
                            ("TAX", "IPVA"),
                            ("OTHER", "Outros custos fixos"),
                        ],
                        max_length=10,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=180, verbose_name="descrição"),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor mensal"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="vigência inicial")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência final"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_costs",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "custo fixo",
                "verbose_name_plural": "custos fixos",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Financing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="parcela mensal",
                    ),
                ),
                (
                    "financial_institution",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="instituição financeira",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data inicial"
                    ),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data final prevista"
                    ),
                ),
                (
                    "installments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantidade de parcelas"
                    ),
                ),
                (
                    "installments_paid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="parcelas pagas"
                    ),
                ),
                (
                    "approximate_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="saldo aproximado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "verbose_name": "financiamento",
                "verbose_name_plural": "financiamentos",
                "ordering": ["truck"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MANAGER", "Gestor"), ("DRIVER", "Motorista")],
                        default="DRIVER",
                        max_length=12,
                        verbose_name="perfil",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="telefone"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_profiles",
                        to="fleet.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuário",
                "verbose_name_plural": "perfis de usuários",
            },
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_contract_code_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_driver_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="remuneration",
            constraint=models.UniqueConstraint(
                fields=("driver", "competence"),
                name="unique_remuneration_driver_competence",
            ),
        ),
        migrations.AddConstraint(
            model_name="truck",
            constraint=models.UniqueConstraint(
                fields=("company", "identification"),
                name="unique_truck_identification_per_company",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["company", "status"], name="fleet_trip_company_90bb6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["company", "started_at"], name="fleet_trip_company_8a1da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fueling",
            index=models.Index(
                fields=["company", "fueled_at"], name="fleet_fueli_company_72834f_idx"
            ),
        ),
    ]
