# Generated by Django 5.2.17 on 2026-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fueling",
            constraint=models.CheckConstraint(
                condition=models.Q(("liters__gt", 0)),
                name="fueling_liters_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fueling",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="fueling_total_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("truck",),
                name="one_open_trip_per_truck",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("driver",),
                name="one_open_trip_per_driver",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_odometer__isnull", True),
                    ("end_odometer__gte", models.F("start_odometer")),
                    _connector="OR",
                ),
                name="trip_end_odometer_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("started_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="trip_end_not_before_start",
            ),
        ),
    ]
