# Generated by Django 5.2.17 on 2026-08-30 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_fueling_fueling_liters_positive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleChecklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="data e hora")),
                ("tires_ok", models.BooleanField(default=True, verbose_name="pneus em condição")),
                ("lights_ok", models.BooleanField(default=True, verbose_name="luzes e sinalização")),
                ("oil_ok", models.BooleanField(default=True, verbose_name="óleo e fluidos")),
                ("brakes_ok", models.BooleanField(default=True, verbose_name="freios")),
                ("documents_ok", models.BooleanField(default=True, verbose_name="documentação")),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="fleet.company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checklists", to="fleet.driver")),
                ("trip", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checklists", to="fleet.trip")),
                ("truck", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checklists", to="fleet.truck")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "checklist do veículo",
                "verbose_name_plural": "checklists dos veículos",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(fields=["company", "checked_at"], name="fleet_vehic_company_028cc9_idx"),
                    models.Index(fields=["truck", "checked_at"], name="fleet_vehic_truck_i_8686f6_idx"),
                ],
            },
        ),
    ]
