# Generated by Django 5.2.17 on 2026-08-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_vehiclechecklist"),
    ]

    operations = [
        migrations.AddField(model_name="trip", name="cargo_description", field=models.CharField(blank=True, max_length=180, verbose_name="carga")),
        migrations.AddField(model_name="trip", name="cargo_weight", field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="peso da carga (kg)")),
        migrations.AddField(model_name="trip", name="delivery_proof", field=models.FileField(blank=True, null=True, upload_to="deliveries/%Y/%m/", verbose_name="comprovante de entrega")),
        migrations.AddField(model_name="trip", name="delivery_reference", field=models.CharField(blank=True, max_length=80, verbose_name="referência de entrega")),
        migrations.AddField(model_name="trip", name="planned_end_at", field=models.DateTimeField(blank=True, null=True, verbose_name="entrega prevista")),
        migrations.AddField(model_name="trip", name="planned_start_at", field=models.DateTimeField(blank=True, null=True, verbose_name="início previsto")),
    ]
