# Generated by Django 5.2.17 on 2026-08-30 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_trip_cargo_description_trip_cargo_weight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(choices=[("PAYABLE", "Conta a pagar"), ("RECEIVABLE", "Conta a receber")], max_length=12, verbose_name="tipo")),
                ("category", models.CharField(max_length=80, verbose_name="categoria")), ("description", models.CharField(max_length=180, verbose_name="descrição")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="valor")), ("due_date", models.DateField(verbose_name="vencimento")),
                ("paid_at", models.DateField(blank=True, null=True, verbose_name="liquidação")),
                ("status", models.CharField(choices=[("PENDING", "Pendente"), ("APPROVED", "Aprovada"), ("PAID", "Liquidada"), ("CANCELLED", "Cancelada")], default="PENDING", max_length=12, verbose_name="situação")),
                ("reference", models.CharField(blank=True, max_length=100, verbose_name="documento/referência")), ("attachment", models.FileField(blank=True, null=True, upload_to="cash/%Y/%m/", verbose_name="anexo")), ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="fleet.company")),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cash_entries", to="fleet.contract")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("truck", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cash_entries", to="fleet.truck")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name":"conta financeira", "verbose_name_plural":"contas financeiras", "ordering":["due_date", "entry_type", "description"], "indexes":[models.Index(fields=["company", "due_date", "status"], name="fleet_cashe_company_0af083_idx"), models.Index(fields=["company", "entry_type", "status"], name="fleet_cashe_company_18cab2_idx")]},
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("maintenance_type", models.CharField(choices=[("PREVENTIVE", "Preventiva"), ("CORRECTIVE", "Corretiva"), ("TIRES", "Pneus"), ("OIL", "Óleo"), ("BRAKES", "Freios"), ("ENGINE", "Motor"), ("ELECTRIC", "Elétrica"), ("OTHER", "Outros")], max_length=12, verbose_name="tipo")),
                ("title", models.CharField(max_length=180, verbose_name="serviço planejado")), ("interval_days", models.PositiveIntegerField(blank=True, null=True, verbose_name="periodicidade em dias")), ("interval_km", models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name="periodicidade em km")),
                ("next_due_date", models.DateField(blank=True, null=True, verbose_name="próxima data")), ("next_due_odometer", models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name="próxima quilometragem")), ("active", models.BooleanField(default=True, verbose_name="ativo")), ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="fleet.company")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)), ("truck", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="maintenance_plans", to="fleet.truck")), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name":"plano preventivo", "verbose_name_plural":"planos preventivos", "ordering":["next_due_date", "next_due_odometer", "title"], "indexes":[models.Index(fields=["company", "active"], name="fleet_maint_company_27b2c4_idx"), models.Index(fields=["truck", "active"], name="fleet_maint_truck_i_d40276_idx")]},
        ),
    ]
